spring.application.name=tp-Foyer
spring.datasource.url=jdbc:mysql://localhost:3306/TpFoyer?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server configuration :
server.port=8088
server.servlet.context-path=/arctic
